export const projects = [
  {
    title: "9Points",
    techStack : "HTML, SCSS, CSS, JavaScript, WOW.js",
    imageMain: '../../img/mainImages/9pointsMain.webp',
    urlDeploy: 'https://9points.netlify.app/',
    github:'https://github.com/francociprian/9POINTS',
    details: 'mb-6',
    imageMobile1 : "../../img/mobileImages/9points.webp",
    imageMobile2 : "../../img/mobileImages/9points1.webp",
    imageMobile3 : "../../img/mobileImages/9points2.webp",
    description: 'Development of a fictitious company that provides software solutions, using HTML for the structure, SCSS for the visual section and basic Javascript for interactions with the page. The BEM methodology was used, and the project was managed using GIT for version control.'
  },
  {
    title: "SocialTree",
    techStack : "ReactJS, Firebase, ChakraUI",
    imageMain: '../../img/mainImages/socialtreeMain1.webp',
    imageMain2: '../../img/mainImages/socialtreeMain2.webp',
    urlDeploy: 'https://socialtreee.vercel.app',
    github:'https://github.com/francociprian/SocialTree',
    details : 'mx-auto mb-12',
    imageMobile1 : "../../img/mobileImages/social-Links1.webp",
    imageMobile2 : "../../img/mobileImages/social-Links2.webp",
    imageMobile3 : "../../img/mobileImages/social-Links3.webp",
    description: 'SocialTree is a social network that allows you to share your links with other users, it was developed using ReactJS, Firebase for the database and ChakraUI for the design.'
  },
  {
    title: "Untraceable",
    techStack : "HTML, Bootstrap, SCSS, JavaScript",
    imageMain : '../../img/mainImages/untraceable1.webp',
    imageMain2: '../../img/mainImages/untraceable2.webp',
    imageMain3: '../../img/mainImages/untraceable3.webp',
    urlDeploy: 'https://untraceable.netlify.app/',
    github:'https://github.com/francociprian/UNTRACEABLE',
    details : 'mx-auto mb-12',
    imageMobile1 : "../../img/mobileImages/untraceable1.webp",
    imageMobile2 : "../../img/mobileImages/untraceable2.webp",
    imageMobile3 : "../../img/mobileImages/untraceable3.webp",
    description: 'Development of an e-commerce, using HTML for the structure, Bootstrap and SCSS for the visual section, the products come from a JSON that simulates the operation of an API. The BEM methodology was used, and the project was managed using GIT.'
  },
  {
    title: "Weather with Franco",
    techStack : "ReactJS, TailwindCSS, OpenWeatherAPI, ChartJS",
    imageMain:  '../../img/mainImages/weatherMain1.webp',
    imageMain2: '../../img/mainImages/weatherMain2.webp',
    imageMain3: '../../img/mainImages/weatherMain3.webp',
    urlDeploy: 'https://weather-with-franco.vercel.app/',
    github:'https://github.com/francociprian/Weather-with-Franco',
    details : 'mx-auto mb-12',
    imageMobile1 : "../../img/mobileImages/weatherWithFranco1.webp",
    imageMobile2 : "../../img/mobileImages/weatherWithFranco2.webp",
    imageMobile3 : "../../img/mobileImages/weatherWithFranco3.webp",
    description: 'Weather with Franco is an application that allows knowing the weather of a city, it was developed using ReactJS, consuming OpenWeatherAPI for the data, ChartJS and TailwindCSS for the design.'
  },
  {
    title: "TodoList",
    techStack : "ReactJS, CSS",
    imageMain: '../../img/mainImages/todolistMain.webp',
    urlDeploy: 'https://taskfranco.vercel.app',
    github:'https://github.com/francociprian/TodoList',
    details : 'mx-auto mb-12',
    imageMobile1 : "../../img/mobileImages/taskList1.webp",
    imageMobile2 : "../../img/mobileImages/taskList2.webp",
    imageMobile3 : "../../img/mobileImages/taskList3.webp",
    description: 'TodoList is a simple application that allows you to add tasks, remove them from the list or mark them as complete. It was developed using ReactJS and CSS for layout.'
  },
  {
    title: "Calculator",
    techStack : "ReactJS, CSS, MATH.js",
    imageMain: '../../img/mainImages/calculadoraMain.webp',
    urlDeploy: 'https://calculatorfrancociprian.netlify.app/',
    github:'https://github.com/francociprian/React-Calculator',
    details : 'mx-auto mb-12',
    imageMobile1 : "../../img/mobileImages/calculator.webp",
    imageMobile2 : "../../img/mobileImages/calculator.webp",
    imageMobile3 : "../../img/mobileImages/calculator1.gif",
    description: 'Calculator is a simple application that allows you to make basic calculations, it was developed using ReactJS, CSS for the design and mathJS for the calculations.'
  },
]